### ISSUE TITLE
 UnicodeDecodeError

### ISSUE THREAD

**Issue by fgianoli** [north-road/qgis-processing-r#123]
I am working with QGIS 3.32.0-Lima on Windows 11. I am trying to port an R script to QGIS by creating an R script.

However, when I run it, I get an encoding error that I can't understand:

`Traceback (most recent call last): File "C:\Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\SGI/python/plugins\processing_r\processing\algorithm.py", line 396, in processAlgorithm output = RUtils.execute_r_algorithm(self, parameters, context, feedback) File "C:\Users/giano/AppData/Roaming/QGIS/QGIS3\profiles\SGI/python/plugins\processing_r\processing\utils.py", line 281, in execute_r_algorithm for line in iter(proc.stdout.readline, ''): File "C:\OSGeo4W\apps\Python39\lib\codecs.py", line 322, in decode (result, consumed) = self._buffer_decode(data, self.errors, final) UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 21: invalid continuation byte Execution failed after 37.93 seconds`

The code I am using is as follows, and I have two input rasters, one with Integer values and the other is float.

In fact, the objective is to perform zonal statistics between rasters by calculating the median of the values of raster A for each class of raster B (which the "Raster Layer Zonal statistics" tool does not do) and then reclassify the values of raster A based on the calculated value.

```
##My scripts=group

##LC=raster
##issue=raster
##output= output raster

library(raster)
library(sf)
library(sp)

x<-resample(issue,LC, method='ngb')
issue <-x

issue <- crop(issue, extent(LC))  
res(issue) <- res(LC)
extent(issue) <- extent(LC)
 
s<- issue
r<- LC
result <- zonal(s, r, 'median')

r2 <- reclassify(r, result)


rc <- function(x) {
 
  x1 <- x[1] 
  x2 <- x[2] 
  ifelse(x1 <=  x2, 0,
  ifelse(x1 >  x2, 1, NA)) }

s2 <- stack(s,r2)

beginCluster(6) 
z1 <- clusterR(s2, calc, args=list(fun=rc))
endCluster()

output<- z1
```

Is this a an error on the code or a bug?

**Comment by JanCaha** [comment]
Would it be possible to run the algorithm in R and post here the output of the algorithm from R console (in R Studio or whatever IDE you use)?

It seems that python has some issues with decoding some of R output lines. But that should not really happen...

**Comment by Penta0308** [comment]
Removing L248 and L249 of processing\utils.py worked.

**Comment by JanCaha** [comment]
@Penta0308  could you in QGIS open python command line, run those commands and report what it returns?  

```
from ctypes import cdll
print(str(cdll.kernel32.GetACP()))
```

Thanks

**Comment by Penta0308** [comment]
@JanCaha I am South Korean, we use CP949 as legacy codepage. Most modern program uses UTF-8, but there's some incompatibility with the `Beta: ... Unicode...`. So basically my windows codepage is CP949. Your code returns `949`.

![Image](https://github.com/user-attachments/assets/7d91aa82-1feb-4cee-86ae-f0e1fc491c2f)

I've set my env var `PYTHONIOENCODING=utf-8` and `PYTHONUTF8=1`, but the codepage detection in processing\utils.py in this repo overrides them and force set CP949.
When I run R code(UTF-8 encoded) that has Hangul(Non-ASCII) char in QGIS, R gives UTF-8 console output. But the python side tries to read the UTF-8 byte stream using CP949 decoder, which triggers a error for me.

Disabling the codepage detection from python by editing py files made it read the Popen stdout as UTF-8, which solved my problem.
