### ISSUE TITLE
Ubuntu 18.04 - Python error right after installation

### ISSUE THREAD

**Issue by fsdias** [north-road/qgis-processing-r#19]
Couldn't load plugin 'processing-r' due to an error when calling its classFactory() method 

ModuleNotFoundError: No module named 'r' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/fd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing-r/__init__.py", line 22, in classFactory
    from .r_plugin import RProviderPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/fd/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing-r/r_plugin.py", line 21, in 
    from r.processing.provider import RAlgorithmProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'r'

Python version: 3.6.7 (default, Oct 22 2018, 11:32:17) [GCC 8.2.0] 
QGIS version: 3.4.3-Madeira Madeira, 19f0e02 

Python Path:
/usr/share/qgis/python
/home/fd/.local/share/QGIS/QGIS3/profiles/default/python
/home/fd/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/fd/.local/share/QGIS/QGIS3/profiles/default/python
/media/fd/Dados/FilipeTrabalho/Riverscale/GIS

**Comment by rhurlin** [comment]
I get the exactly same error on FreeBSD 13.0-CURRENT amd64 with QGIS 3.5.0-Master (also 3.4.3 [1]). Only the Python version is somewhat newer:

Python-Version: 3.6.8 (default, Jan  1 2019, 14:25:16) [GCC 4.2.1 Compatible FreeBSD Clang 7.0.1 (tags/RELEASE_701/final 349250)] 
QGIS-Version: 3.5.0-Master Master, exported 

[1] https://www.freshports.org/graphics/qgis

**Comment by nyalldawson** [comment]
Fixed in plugin version 1.0.1 -- note that you'll need to reinstall the plugin, as I had to remove the existing version of the plugin in order to fix this and publish as a whole new plugin (so the update notification won't work for this upgrade)

**Comment by rhurlin** [comment]
Fixed on FreeBSD, thanks a lot for the quick patch :)
