### ISSUE TITLE
Permission denied on FreeBSD for version 1.0.1 on QGIS 3.5.0-Master

### ISSUE THREAD

**Issue by rhurlin** [north-road/qgis-processing-r#22]
I am on FreeBSD with QGIS 3.5.0-Master and 'Processing R Provider' plugin version 1.0.1. It installs fine. My R version is at /usr/local/lib under root rights. Personally installed R libraries (not from R itself) are in my user section under /usr/home/rhurlin/R/library.

Right after starting QGIS, which loads installed plugins, there are three Python warnings in the log messages (please read on after these three warnings for a possible reason and an error description):

**From log messages 'Python warning'**
```
2019-01-26T12:27:41     WARNING    warning:/usr/local/share/qgis/python/plugins/processing/gui/wrappers.py:1777: DeprecationWarning: invalid escape sequence \A
              match = re.search('(?:\A|[^0-9]){}(?:\Z|[^0-9]|)'.format(v), opt)
             
             traceback: File "", line 1, in 
              File "/usr/local/share/qgis/python/qgis/utils.py", line 335, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/__init__.py", line 22, in classFactory
              from .r_plugin import RProviderPlugin
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/r_plugin.py", line 21, in 
              from processing_r.processing.provider import RAlgorithmProvider
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/provider.py", line 26, in 
              from processing.core.ProcessingConfig import ProcessingConfig, Setting
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 941, in _find_and_load_unlocked
              File "", line 219, in _call_with_frames_removed
              File "", line 971, in _find_and_load
              File "", line 941, in _find_and_load_unlocked
              File "", line 219, in _call_with_frames_removed
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/__init__.py", line 29, in 
              from processing.tools.general import * # NOQA
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/tools/general.py", line 39, in 
              from processing.core.Processing import Processing
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/core/Processing.py", line 58, in 
              from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider # NOQA
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/QgisAlgorithmProvider.py", line 81, in 
              from .IdwInterpolation import IdwInterpolation
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/IdwInterpolation.py", line 44, in 
              from processing.algs.qgis.ui.InterpolationWidgets import ParameterInterpolationData, ParameterPixelSize
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/ui/InterpolationWidgets.py", line 49, in 
              from processing.gui.wrappers import WidgetWrapper, DIALOG_STANDARD
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 674, in exec_module
              File "", line 781, in get_code
              File "", line 741, in source_to_code
              File "", line 219, in _call_with_frames_removed
             
2019-01-26T12:27:41     WARNING    warning:/usr/local/share/qgis/python/plugins/processing/gui/wrappers.py:1792: DeprecationWarning: invalid escape sequence \A
              match = re.search('(?:\A|[^0-9])([0-9]+)(?:\Z|[^0-9]|)', self.widget.options[i])
             
             traceback: File "", line 1, in 
              File "/usr/local/share/qgis/python/qgis/utils.py", line 335, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/__init__.py", line 22, in classFactory
              from .r_plugin import RProviderPlugin
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/r_plugin.py", line 21, in 
              from processing_r.processing.provider import RAlgorithmProvider
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/provider.py", line 26, in 
              from processing.core.ProcessingConfig import ProcessingConfig, Setting
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 941, in _find_and_load_unlocked
              File "", line 219, in _call_with_frames_removed
              File "", line 971, in _find_and_load
              File "", line 941, in _find_and_load_unlocked
              File "", line 219, in _call_with_frames_removed
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/__init__.py", line 29, in 
              from processing.tools.general import * # NOQA
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/tools/general.py", line 39, in 
              from processing.core.Processing import Processing
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/core/Processing.py", line 58, in 
              from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider # NOQA
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/QgisAlgorithmProvider.py", line 81, in 
              from .IdwInterpolation import IdwInterpolation
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/IdwInterpolation.py", line 44, in 
              from processing.algs.qgis.ui.InterpolationWidgets import ParameterInterpolationData, ParameterPixelSize
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/ui/InterpolationWidgets.py", line 49, in 
              from processing.gui.wrappers import WidgetWrapper, DIALOG_STANDARD
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 674, in exec_module
              File "", line 781, in get_code
              File "", line 741, in source_to_code
              File "", line 219, in _call_with_frames_removed
             
2019-01-26T12:27:41     WARNING    warning:/usr/local/lib/python3.6/site-packages/PyQt5/uic/objcreator.py:152: DeprecationWarning: 'U' mode is deprecated
              plugin = open(filename, 'rU')
             
             traceback: File "", line 1, in 
              File "/usr/local/share/qgis/python/qgis/utils.py", line 335, in startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/__init__.py", line 22, in classFactory
              from .r_plugin import RProviderPlugin
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/r_plugin.py", line 21, in 
              from processing_r.processing.provider import RAlgorithmProvider
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/provider.py", line 26, in 
              from processing.core.ProcessingConfig import ProcessingConfig, Setting
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 941, in _find_and_load_unlocked
              File "", line 219, in _call_with_frames_removed
              File "", line 971, in _find_and_load
              File "", line 941, in _find_and_load_unlocked
              File "", line 219, in _call_with_frames_removed
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/__init__.py", line 29, in 
              from processing.tools.general import * # NOQA
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/tools/general.py", line 39, in 
              from processing.core.Processing import Processing
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/core/Processing.py", line 58, in 
              from processing.algs.qgis.QgisAlgorithmProvider import QgisAlgorithmProvider # NOQA
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/QgisAlgorithmProvider.py", line 81, in 
              from .IdwInterpolation import IdwInterpolation
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/IdwInterpolation.py", line 44, in 
              from processing.algs.qgis.ui.InterpolationWidgets import ParameterInterpolationData, ParameterPixelSize
              File "/usr/local/share/qgis/python/qgis/utils.py", line 672, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 971, in _find_and_load
              File "", line 955, in _find_and_load_unlocked
              File "", line 665, in _load_unlocked
              File "", line 678, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/usr/local/share/qgis/python/plugins/processing/algs/qgis/ui/InterpolationWidgets.py", line 93, in 
              WIDGET, BASE = uic.loadUiType(os.path.join(pluginPath, 'interpolationdatawidgetbase.ui'))
              File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/__init__.py", line 198, in loadUiType
              winfo = compiler.UICompiler().compileUi(uifile, code_string, from_imports, resource_suffix, import_from)
              File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/Compiler/compiler.py", line 53, in __init__
              qtproxies.QtWidgets, CompilerCreatorPolicy())
              File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/uiparser.py", line 177, in __init__
              self.factory = QObjectCreator(creatorPolicy)
              File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/objcreator.py", line 85, in __init__
              if self.load_plugin(filename, plugin_globals, plugin_locals):
              File "/usr/local/lib/python3.6/site-packages/PyQt5/uic/objcreator.py", line 152, in load_plugin
              plugin = open(filename, 'rU')
```

----------------------------------------------------------------------------
If I try to run the 'test' script, I get a breakage with the following error:

**Stack trace**
```
An error has occurred while executing Python code: 

PermissionError: [Errno 13] Permission denied: '/usr/local/lib/R' 
Traceback (most recent call last):
  File "/usr/local/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 223, in executeAlgorithm
    ok, message = alg.canExecute()
  File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/algorithm.py", line 272, in canExecute
    msg = RUtils.check_r_is_installed()
  File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/utils.py", line 316, in check_r_is_installed
    universal_newlines=True) as proc:
  File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/R'

Python version: 3.6.8 (default, Jan  1 2019, 14:25:16) [GCC 4.2.1 Compatible FreeBSD Clang 7.0.1 (tags/RELEASE_701/final 349250)] 
QGIS version: 3.5.0-Master Master, exported 

Python Path:
/usr/local/share/qgis/python
/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python
/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/share/qgis/python/plugins
/usr/local/lib/python36.zip
/usr/local/lib/python3.6
/usr/local/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/site-packages
/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python
```

**Log Messages 'Python error'**
```
2019-01-26T12:14:16     WARNING    Traceback (most recent call last):
              File "/usr/local/share/qgis/python/plugins/processing/gui/ProcessingToolbox.py", line 223, in executeAlgorithm
              ok, message = alg.canExecute()
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/algorithm.py", line 272, in canExecute
              msg = RUtils.check_r_is_installed()
              File "/home/rhurlin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_r/processing/utils.py", line 316, in check_r_is_installed
              universal_newlines=True) as proc:
              File "/usr/local/lib/python3.6/subprocess.py", line 729, in __init__
              restore_signals, start_new_session)
              File "/usr/local/lib/python3.6/subprocess.py", line 1364, in _execute_child
              raise child_exception_type(errno_num, err_msg, err_filename)
             PermissionError: [Errno 13] Permission denied: '/usr/local/lib/R'
```

Because of the three warnings during the loading of the module, I assume there is a bigger problem than only access rights for /usr/local/lib?

Any help is really appreciated, many thanks.

**Comment by nyalldawson** [comment]
The warnings aren't related -- those are caused from external python libraries and shouldn't hurt anything.

Regarding "Permission denied: '/usr/local/lib/R' ": this means the plugin can't run that command. I can't diagnose this myself -- can you do some troubleshooting with permissions and see why this would be the case?

**Comment by nyalldawson** [comment]
Closed due to lack of feedback
